etherbotix:
  ros__parameters:
    default_controllers:
      - "base_controller"
      - "lr_wheel_mimic"
      - "rr_wheel_mimic"
    base_controller:
      type: "robot_controllers/DiffDriveBaseController"
      max_velocity_x: 0.5
      max_acceleration_x: 1.0
      # Base width in meters
      track_width: 0.2667
      # 4.7" wheels = 0.3750m rollout = 2.66 rotations / meter
      radians_per_meter: 16.753
      # hold position
      moving_threshold: -0.01
      rotating_threshold: -0.01
      # autostart to get odom
      autostart: true
      # name of joints
      l_wheel_joints:
        - "lf_wheel_joint"
      r_wheel_joints:
        - "rf_wheel_joint"
    lr_wheel_mimic:
      type: "robot_controllers/ScaledMimicController"
      mimic_joint: "lf_wheel_joint"
      controlled_joint: "lr_wheel_joint"
      autostart: true
    rr_wheel_mimic:
      type: "robot_controllers/ScaledMimicController"
      mimic_joint: "rf_wheel_joint"
      controlled_joint: "rr_wheel_joint"
      autostart: true
    # 64cpr*50:1
    ticks_per_radian: 509.3
    # Using external UM-7 IMU
    imu: false
    # Tuned on April 17, 2020
    motor_kp: 10.0
    motor_kd: 0.0
    motor_ki: 1.5
    motor_kw: 950.0
    # Name for joints
    l_motor_name: "lf_wheel_joint"
    r_motor_name: "rf_wheel_joint"
