joints: {
  # TODO: these are not fully defined
  head_pan_joint: {type: dynamixel, id: 1},
  head_tilt_joint: {type: dynamixel, id: 2},
  laser_tilt_joint: {type: dynamixel, id: 3},
}
controllers: {
  # Robomagellan Base: 4.7" Wheels = 0.3748m * pi, 64*100cpr
  # base width doesn't really make physical sense, but works.
  base_controller: {type: diff_controller, base_width: 0.109375, ticks_meter: 17073, Kp: 1.5},
}
imu: true
