controllers: {
  base_controller: {
    type: diff_controller,
    # joint names
    left_joint_name: lf_wheel_joint,
    right_joint_name: rf_wheel_joint,
    left_joint_mimic: lr_wheel_joint,
    right_joint_mimic: rr_wheel_joint,
    # Base width in meters
    base_width: 0.2667,
    # Robomagellan Base: 4.7" Wheels = 0.3750m rollout, 64cpr*50:1
    ticks_meter: 8532,
    # Ticks per rollout: 64cpr * 50:1 gearing
    ticks_rotation: 3200,
    # Tuned on April 17, 2020
    Kp: 10.0,
    Kd: 0.0,
    Ki: 1.5,
    Kw: 950.0,
    # TBD
    accel_limit: 1.0,
    # 200rpm * 0.375m rollout
    max_velocity: 1.0,
    # robot_localization handles TF
    publish_tf: false,
    # tank drive sux
    covariance_wz: 0.01
  },
}
# Using external UM-7 IMU
imu: false
