planar_output: True # Output only x, y, and rotation about z

output_frame: odom # TF frame id, param name ported from robot_pose_ekf
parent_frame_id: odom # TF frame id, override output_frame if set
child_frame_id: test_link #TF frame id

freq: 10.0 # In Hz, param name ported from robot_pose_ekf
update_rate: 10.0 # Overides 'freq' if set, in Hz
update_topic: odom # Which topic to trigger updates, if blank, uses timed update_rate, if '*', will trigger on all new topics

dt_override : 0.0 # Override the dt for update_rate or update_topic, ignored if 0

queue_size: 1

publish_tf: true

# Filter parameters

alpha: 0.001
kappa: 0.0
beta: 2.0

# Process noise covariance 2x2 for velocites, 5x5 for 2d position
process_noise: [1e6, 0, 0,
                0, 1e6, 0,
                0, 0, 1e6]

topics: {
  odom: {
    topic: /odom,
    type: nav_msgs/Odometry,
    absolute_pose: False,
    use_velocities: True,
    timeout: 1.0,
  },

  imu: {
    topic: /imu_biased,
    type: sensor_msgs/Imu,
    absolute_orientation: False,
    use_velocities: True,
    use_accelerations: False,
    timeout: 1.0,
  },
}
