ground_filter:
  ros__parameters:
    robot_frame: 'base_link'
    fixed_frame: 'odom'
    transform_timeout: 0.2

    cell_size: 0.125
    grid_size: 16.0
    cell:
      min_points: 8
      planar_tolerance: 0.1

    # TODO: turn this off for competition
    debug_topics: true
